In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import copy

In [2]:
class State:
    def __init__(self, current_player="MAX"):
        self.game_board = self.initial_game_board()
        self.current_player = current_player
        
    def initial_game_board(self):
        initial_state = np.zeros(shape=(4,4), dtype=np.int32)
        initial_state[0,0] = 1
        initial_state[1,1] = 1
        initial_state[2,2] = 1
        initial_state[3,3] = 1
        initial_state[0,3] = -1
        initial_state[1,2] = -1
        initial_state[2,1] = -1
        initial_state[3,0] = -1
        return initial_state

In [3]:
max_limit = 3
min_limit = 0

def out_of_boundaries(pos):
    return pos < min_limit or pos > max_limit

def not_out_of_limits(row, column):
    return not out_of_boundaries(row) and not out_of_boundaries(column)

def down_function(row, column):
    return row+1, column

def up_function(row, column):
    return row-1, column

def left_function(row, column):
    return row, column-1

def right_function(row, column):
    return row, column+1

def up_left_function(row, column):
    return row-1, column-1

def up_right_function(row, column):
    return row-1, column+1

def down_left_function(row, column):
    return row+1, column-1

def down_right_function(row, column):
    return row+1, column+1

#def up_left_function(row, column):
    #return up_function(*left_function(row, column))

#def up_right_function(row, column):
    #return up_function(*right_function(row, column))

#def down_left_function(row, column):
    #return down_function(*left_function(row, column))

#def down_right_function(row, column):
    #return down_function(*right_function(row, column))

def move_function(state, value, row, col, move_func):
    # Check if row and column are within limits
    # Check if the value at (row, col) is the same as the given value
    if not_out_of_limits(row, col) and state.game_board[row, col] == value:
            # Get the new row and column based on the move function
            new_row, new_col = move_func(row, col)
            # Check if the new position is within limits and is free from other player
            if not_out_of_limits(new_row, new_col) and state.game_board[new_row, new_col] == 0:
                # Move the value to the new position
                state.game_board[new_row, new_col] = value
                # Set the old position to 0
                state.game_board[row, col] = 0
    # Return the updated state
    return state

In [4]:
a = State("MAX")
print(a.game_board)
print("-------------")
print(move_function(a, 1, 0, 0, down_function).game_board)
print("-------------")
print(move_function(a, -1, 2, 1, down_right_function).game_board)
#print(move_function(a, -1, 1, 2, right_function).game_board)
#print("-------------")
#print(move_function(a, 1, 1, 1, left_function).game_board)
#print("-------------")
#print(move_function(a, -1, 2, 1, down_function).game_board)

[[ 1  0  0 -1]
 [ 0  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0  0  1  0]
 [-1  0 -1  1]]
