In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import copy

In [2]:
# "MAX" = -1
# "MIN" = 1

class State:
    def __init__(self, current_player="MAX"):
        self.game_board = self.initial_game_board()
        self.current_player = current_player
        
    def initial_game_board(self):
        initial_state = np.zeros(shape=(4,4), dtype=np.int32)
        initial_state[0,0] = 1
        initial_state[1,1] = 1
        initial_state[2,2] = 1
        initial_state[3,3] = 1
        initial_state[0,3] = -1
        initial_state[1,2] = -1
        initial_state[2,1] = -1
        initial_state[3,0] = -1
        return initial_state
    
    def get_value(self):
        if self.current_player == "MAX":
            return -1
        elif self.current_player == "MIN":
            return 1
    
    def set_value(self, row, col, value):
        self.game_board[row, col] = value
    
    def is_player_disk(self, row, col, value):
        return self.game_board[row, col] == value and self.game_board[row, col] != 0
    
    def is_free_space(self, row, col):
        return self.game_board[row, col] == 0

In [3]:
max_limit = 3
min_limit = 0

def out_of_boundaries(pos):
    return pos < min_limit or pos > max_limit

def not_out_of_limits(row, column):
    return not out_of_boundaries(row) and not out_of_boundaries(column)

def down_function(row, column):
    return row+1, column

def up_function(row, column):
    return row-1, column

def left_function(row, column):
    return row, column-1

def right_function(row, column):
    return row, column+1

def up_left_function(row, column):
    return row-1, column-1

def up_right_function(row, column):
    return row-1, column+1

def down_left_function(row, column):
    return row+1, column-1

def down_right_function(row, column):
    return row+1, column+1

#def up_left_function(row, column):
    #return up_function(*left_function(row, column))

#def up_right_function(row, column):
    #return up_function(*right_function(row, column))

#def down_left_function(row, column):
    #return down_function(*left_function(row, column))

#def down_right_function(row, column):
    #return down_function(*right_function(row, column))

def move_function(state, value, row, col, move_func):
    # Check if row and column are within limits
    # Check if the value at (row, col) is the same as the given value
    if not_out_of_limits(row, col) and state.is_player_disk(row, col, value):
            # Get the new row and column based on the move function
            new_row, new_col = move_func(row, col)
            # Check if the new position is within limits and is free from other player
            if not_out_of_limits(new_row, new_col) and state.is_free_space(new_row, new_col):
                # Move the value to the new position
                state.set_value(new_row, new_col, value)
                # Set the old position to 0
                state.set_value(row, col, 0)
    # Return the updated state
    return state

def move_function_2(state, value, row, col, move_func):
    # Check if row and column are within limits
    # Check if the value at (row, col) is the same as the given value
    if not_out_of_limits(row, col) and state.is_player_disk(row, col, value):
            # Get the new row and column based on the move function
            new_row, new_col = move_func(row, col)
            # Check if the new position is within limits and is free from other player
            if not_out_of_limits(new_row, new_col) and state.is_free_space(new_row, new_col):
                # Move the value to the new position
                state.set_value(new_row, new_col, value)
                # Set the old position to 0
                state.set_value(row, col, 0)
    # Return the updated state
    return state

In [4]:
a = State()
print(a.game_board)
print("-------------")
print(move_function(a, 1, 0, 0, down_function).game_board)
print("-------------")
print(move_function(a, -1, 2, 1, down_right_function).game_board)
#print(move_function(a, -1, 1, 2, right_function).game_board)
#print("-------------")
#print(move_function(a, 1, 1, 1, left_function).game_board)
#print("-------------")
#print(move_function(a, -1, 2, 1, down_function).game_board)

[[ 1  0  0 -1]
 [ 0  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0  0  1  0]
 [-1  0 -1  1]]


In [5]:
def possible_move_function(state, value, row, col, move_func):
    copy_state = copy.deepcopy(state)
    sucess = False
    # Get the new row and column based on the move function
    new_row, new_col = move_func(row, col)
    # Check if is player disk, if is free from other player and the new position in copy is within limits
    if not_out_of_limits(new_row, new_col) and copy_state.is_player_disk(row, col, value) and copy_state.is_free_space(new_row, new_col):
        # Check if is possible move
        sucess = True
    else:
        #print('Is not possible, going back')
        new_row = row
        new_col = col
    # Return if is possible move, new positon [row,column]
    return sucess, new_row, new_col

In [6]:
#TEST
moves = [up_function,down_function,left_function,right_function,up_left_function,up_right_function,down_left_function,down_right_function]

def get_possible_actions(state, value, row, column, game=np.zeros(shape=(4,4), dtype=np.int32), debug=False):
    possible_actions = copy.deepcopy(game)
    for move in moves:
        success, possible_move_row, possible_move_column = possible_move_function(state, value, row, column, move)
        if success:
            #possible_actions[row, column] = value
            possible_actions[possible_move_row, possible_move_column] = value
            #possible_actions[possible_move_row, possible_move_column] = 1
            if debug:
                print(move)
                print(possible_actions)
    return possible_actions

In [7]:
game = get_possible_actions(State(), 1, 0, 0, np.zeros(shape=(4,4), dtype=np.int32), True)

<function down_function at 0x00000273B95674C0>
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<function right_function at 0x00000273B95678B0>
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
map_values = {0:"A", 1:"B", 2:"C", 3:"D"}

def actions(state):
    possible_actions_matrix = np.zeros(shape=(4,4), dtype=np.int32)
    value = state.get_value()
    pos_values_player = np.argwhere(state.game_board == value)
    #print('Tuple pos: \n', pos_values_player, '\nwhere value: ', value)
    pos_values_player = [(pos[0], pos[1]) for pos in pos_values_player]
    for pos in pos_values_player:
        possible_actions_matrix = get_possible_actions(state, value, pos[0], pos[1], possible_actions_matrix)
    pos_possible_actions_player = np.argwhere(possible_actions_matrix == value)
    pos_possible_actions_player = [(pos[0], pos[1]) for pos in pos_possible_actions_player]
    pos_possible_actions_player = [str(map_values[pos[1]] + str(pos[0]+1)) for pos in pos_possible_actions_player]
    return pos_possible_actions_player, possible_actions_matrix

In [21]:
state = State()
state.current_player = "MAX"
print(state.current_player)
possible_actions, matrix = actions(state)
print('#Actions =', len(possible_actions), possible_actions)
print(matrix)

state.current_player = "MIN"
print(state.current_player)
possible_actions, matrix = actions(state)
print('#Actions =', len(possible_actions), possible_actions)
print(matrix)

MAX
#Actions = 8 ['B1', 'C1', 'A2', 'D2', 'A3', 'D3', 'B4', 'C4']
[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]
MIN
#Actions = 8 ['B1', 'C1', 'A2', 'D2', 'A3', 'D3', 'B4', 'C4']
[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]
