In [15]:
import numpy as np
import math
import matplotlib.pyplot as plt
import copy

In [16]:
class State:
    def __init__(self, current_player="MAX"):
        self.game_board = self.initial_game_board()
        self.current_player = current_player
        
    def initial_game_board(self):
        initial_state = np.zeros(shape=(4,4), dtype=np.int32)
        initial_state[0,0] = 1
        initial_state[1,1] = 1
        initial_state[2,2] = 1
        initial_state[3,3] = 1
        initial_state[0,3] = -1
        initial_state[1,2] = -1
        initial_state[2,1] = -1
        initial_state[3,0] = -1
        return initial_state
    
    def set_value(self, row, col, value):
        self.game_board[row, col] = value
    
    def is_player_disk(self, row, col, value):
        return self.game_board[row, col] == value
    
    def is_free_space(self, row, col):
        return self.game_board[row, col] == 0

In [17]:
max_limit = 3
min_limit = 0

def out_of_boundaries(pos):
    return pos < min_limit or pos > max_limit

def not_out_of_limits(row, column):
    return not out_of_boundaries(row) and not out_of_boundaries(column)

def down_function(row, column):
    return row+1, column

def up_function(row, column):
    return row-1, column

def left_function(row, column):
    return row, column-1

def right_function(row, column):
    return row, column+1

def up_left_function(row, column):
    return row-1, column-1

def up_right_function(row, column):
    return row-1, column+1

def down_left_function(row, column):
    return row+1, column-1

def down_right_function(row, column):
    return row+1, column+1

#def up_left_function(row, column):
    #return up_function(*left_function(row, column))

#def up_right_function(row, column):
    #return up_function(*right_function(row, column))

#def down_left_function(row, column):
    #return down_function(*left_function(row, column))

#def down_right_function(row, column):
    #return down_function(*right_function(row, column))

def move_function(state, value, row, col, move_func):
    # Check if row and column are within limits
    # Check if the value at (row, col) is the same as the given value
    if not_out_of_limits(row, col) and state.is_player_disk(row, col, value):
            # Get the new row and column based on the move function
            new_row, new_col = move_func(row, col)
            # Check if the new position is within limits and is free from other player
            if not_out_of_limits(new_row, new_col) and state.is_free_space(new_row, new_col):
                # Move the value to the new position
                state.set_value(new_row, new_col, value)
                # Set the old position to 0
                state.set_value(row, col, 0)
    # Return the updated state
    return state

In [18]:
a = State("MAX")
print(a.game_board)
print("-------------")
print(move_function(a, 1, 0, 0, down_function).game_board)
print("-------------")
print(move_function(a, -1, 2, 1, down_right_function).game_board)
#print(move_function(a, -1, 1, 2, right_function).game_board)
#print("-------------")
#print(move_function(a, 1, 1, 1, left_function).game_board)
#print("-------------")
#print(move_function(a, -1, 2, 1, down_function).game_board)

[[ 1  0  0 -1]
 [ 0  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0 -1  1  0]
 [-1  0  0  1]]
-------------
[[ 0  0  0 -1]
 [ 1  1 -1  0]
 [ 0  0  1  0]
 [-1  0 -1  1]]


In [19]:
def possible_move_function(state, value, row, col, move_func):
    copy_state = copy.deepcopy(state)
    sucess = False
    # Get the new row and column based on the move function
    new_row, new_col = move_func(row, col)
    # Check if is player disk, if is free from other player and the new position in copy is within limits
    if not_out_of_limits(new_row, new_col) and copy_state.is_player_disk(row, col, value) and copy_state.is_free_space(new_row, new_col):
        # Check if is possible move
        sucess = True
    else:
        #print('Is not possible, going back')
        new_row = row
        new_col = col
    # Return if is possible move, new positon [row,column]
    return sucess, new_row, new_col

In [20]:
moves = [up_function,down_function,left_function,right_function,up_left_function,up_right_function,down_left_function,down_right_function]

def get_possible_actions(state, value, row, column, game=np.zeros(shape=(4,4), dtype=np.int32)):
    possible_actions = copy.deepcopy(game)
    for move in moves:
        success, possible_move_row, possible_move_column = possible_move_function(state, value, row, column, move)
        if success:
            possible_actions[row, column] = value
            possible_actions[possible_move_row, possible_move_column] = 4
            print(move)
            print(possible_actions)
    return possible_actions

In [21]:
game = get_possible_actions(State(), 1, 1, 1, np.zeros(shape=(4,4), dtype=np.int32))

<function up_function at 0x00000236FF6159D0>
[[0 4 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<function left_function at 0x00000236FF615940>
[[0 4 0 0]
 [4 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<function up_right_function at 0x0000023680223040>
[[0 4 4 0]
 [4 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<function down_left_function at 0x00000236802230D0>
[[0 4 4 0]
 [4 1 0 0]
 [4 0 0 0]
 [0 0 0 0]]
